// Autogenerated image mapping data
window.imageMapping = {
  "2.7": [
    "page_25_img_1.png"
  ],
  "2.9": [
    "page_25_img_1.png"
  ],
  "2.22": [
    "page_28_img_1.png"
  ],
  "2.23": [
    "page_28_img_1.png"
  ],
  "2.24": [
    "page_29_img_1.png"
  ],
  "2.26": [
    "page_29_img_1.png"
  ],
  "2.27": [
    "page_29_img_1.png"
  ],
  "2.31": [
    "page_30_img_1.png"
  ],
  "2.32": [
    "page_30_img_1.png"
  ],
  "2.33": [
    "page_30_img_1.png"
  ],
  "3.6": [
    "page_38_img_1.png"
  ],
  "3.12": [
    "page_40_img_1.png"
  ],
  "3.13": [
    "page_41_img_1.png"
  ],
  "3.14": [
    "page_41_img_1.png"
  ],
  "3.15": [
    "page_41_img_1.png"
  ],
  "3.16": [
    "page_41_img_1.png"
  ],
  "3.27": [
    "page_44_img_1.png"
  ],
  "3.28": [
    "page_44_img_1.png"
  ],
  "3.29": [
    "page_44_img_1.png"
  ],
  "3.30": [
    "page_44_img_1.png"
  ],
  "3.66": [
    "page_52_img_1.png"
  ],
  "4.10": [
    "page_56_img_1.png"
  ],
  "4.11": [
    "page_56_img_1.png"
  ],
  "4.12": [
    "page_57_img_1.png"
  ],
  "4.13": [
    "page_57_img_1.png"
  ],
  "4.16": [
    "page_59_img_1.png"
  ],
  "4.17": [
    "page_59_img_1.png"
  ],
  "4.18": [
    "page_59_img_1.png"
  ],
  "4.19": [
    "page_60_img_1.png"
  ],
  "4.20": [
    "page_60_img_1.png"
  ],
  "4.21": [
    "page_60_img_1.png"
  ],
  "4.27": [
    "page_62_img_1.png"
  ],
  "4.28": [
    "page_62_img_1.png"
  ],
  "4.29": [
    "page_63_img_1.png"
  ],
  "4.30": [
    "page_63_img_1.png"
  ],
  "4.31": [
    "page_63_img_1.png"
  ],
  "4.32": [
    "page_63_img_1.png"
  ],
  "4.33": [
    "page_64_img_1.png"
  ],
  "4.34": [
    "page_64_img_1.png"
  ],
  "4.35": [
    "page_64_img_1.png"
  ],
  "4.40": [
    "page_66_img_1.png"
  ],
  "4.41": [
    "page_66_img_1.png"
  ],
  "4.42": [
    "page_66_img_1.png"
  ],
  "5.7": [
    "page_73_img_1.png"
  ],
  "5.8": [
    "page_73_img_1.png"
  ],
  "5.9": [
    "page_73_img_1.png"
  ],
  "5.10": [
    "page_73_img_1.png"
  ],
  "5.30": [
    "page_78_img_1.png"
  ],
  "5.39": [
    "page_80_img_1.png"
  ],
  "5.42": [
    "page_80_img_1.png"
  ],
  "5.45": [
    "page_81_img_1.png"
  ],
  "5.58": [
    "page_84_img_1.png"
  ],
  "8.4": [
    "page_116_img_1.png"
  ],
  "8.7": [
    "page_117_img_1.png"
  ],
  "10.26": [
    "page_139_img_1.png"
  ],
  "10.54": [
    "page_145_img_1.png"
  ],
  "10.55": [
    "page_145_img_1.png"
  ],
  "10.56": [
    "page_145_img_1.png"
  ],
  "10.66": [
    "page_148_img_1.png"
  ],
  "10.69": [
    "page_149_img_1.png"
  ],
  "10.74": [
    "page_151_img_1.png"
  ],
  "10.77": [
    "page_152_img_1.png"
  ],
  "10.78": [
    "page_153_img_1.png"
  ],
  "10.81": [
    "page_155_img_1.png"
  ],
  "10.82": [
    "page_156_img_1.png",
    "page_156_img_2.png"
  ],
  "10.84": [
    "page_156_img_1.png",
    "page_156_img_2.png"
  ],
  "10.86": [
    "page_157_img_1.png",
    "page_157_img_2.png"
  ],
  "10.87": [
    "page_158_img_1.png",
    "page_158_img_2.png"
  ],
  "10.88": [
    "page_158_img_1.png",
    "page_158_img_2.png"
  ],
  "10.91": [
    "page_159_img_1.png"
  ],
  "10.92": [
    "page_160_img_1.png"
  ],
  "10.93": [
    "page_160_img_1.png"
  ],
  "10.94": [
    "page_160_img_1.png"
  ],
  "10.95": [
    "page_160_img_1.png"
  ],
  "10.96": [
    "page_161_img_1.png"
  ],
  "10.97": [
    "page_162_img_1.png"
  ],
  "10.98": [
    "page_163_img_1.png"
  ],
  "10.99": [
    "page_164_img_1.png"
  ],
  "10.100": [
    "page_165_img_1.png"
  ],
  "10.101": [
    "page_166_img_1.png"
  ],
  "10.102": [
    "page_167_img_1.png"
  ],
  "10.103": [
    "page_168_img_1.png",
    "page_168_img_2.png"
  ],
  "10.104": [
    "page_168_img_1.png",
    "page_168_img_2.png"
  ],
  "10.111": [
    "page_170_img_1.png"
  ],
  "10.112": [
    "page_170_img_1.png"
  ],
  "10.113": [
    "page_170_img_1.png"
  ],
  "10.114": [
    "page_171_img_1.png",
    "page_171_img_2.png"
  ],
  "10.115": [
    "page_171_img_1.png",
    "page_171_img_2.png"
  ],
  "11.11": [
    "page_177_img_1.png"
  ],
  "11.12": [
    "page_178_img_1.png"
  ],
  "11.13": [
    "page_178_img_1.png"
  ],
  "11.29": [
    "page_182_img_1.png"
  ],
  "11.30": [
    "page_182_img_1.png"
  ],
  "11.31": [
    "page_182_img_1.png"
  ],
  "11.42": [
    "page_185_img_1.png"
  ],
  "11.43": [
    "page_186_img_1.png"
  ],
  "11.44": [
    "page_187_img_1.png"
  ],
  "11.45": [
    "page_188_img_1.png"
  ],
  "11.46": [
    "page_188_img_1.png"
  ],
  "11.47": [
    "page_189_img_1.png"
  ],
  "11.48": [
    "page_189_img_1.png"
  ],
  "11.49": [
    "page_189_img_1.png"
  ],
  "11.50": [
    "page_190_img_1.png"
  ],
  "11.51": [
    "page_190_img_1.png"
  ],
  "12.55": [
    "page_202_img_1.png"
  ],
  "12.56": [
    "page_203_img_1.png"
  ],
  "12.57": [
    "page_204_img_1.png"
  ],
  "12.58": [
    "page_205_img_1.png"
  ],
  "12.59": [
    "page_206_img_1.png"
  ],
  "12.60": [
    "page_207_img_1.png"
  ],
  "12.61": [
    "page_208_img_1.png"
  ],
  "12.62": [
    "page_208_img_1.png"
  ],
  "12.63": [
    "page_208_img_1.png"
  ],
  "12.71": [
    "page_211_img_1.png"
  ],
  "12.72": [
    "page_212_img_1.png"
  ],
  "12.73": [
    "page_212_img_1.png"
  ],
  "14.42": [
    "page_233_img_1.png"
  ],
  "14.51": [
    "page_235_img_1.png"
  ],
  "14.53": [
    "page_236_img_1.png"
  ],
  "14.55": [
    "page_238_img_1.png"
  ]
};
